main/views.py
# main / views.py
from flask import Blueprint, request, render_template
from main.utils import PostsManager
from config import POST_PATH
from exceptions import DataLayerError
import logging

# Init new blueprint
main_blueprint = Blueprint('main_blueprint', __name__, template_folder='templates')


# view /
@main_blueprint.route('/')
def page_index():
    logging.info("Главная страница запрошена")
    return render_template("index.html")


# view /search
@main_blueprint.route('/search')
def page_search():

    req = request.args['s']
    logging.info(f"Запрошен поиск постов по слову: {req}")

    post_manager = PostsManager(POST_PATH)

    try:
        posts_by_word = post_manager.get_post_by_word(req)
        if posts_by_word:
            logging.info(f"Найдено {len(posts_by_word)} постов")
            return render_template("post_list.html", query=req, posts=posts_by_word)
        else:
            logging.info(f"Постов не найдено")
            return f"По запросу {req} ничего ненайдено"
    except DataLayerError:
        logging.info(f"Возникла ошибка с чтением из файла")
        return "Ошибка чтения файла с данными"

main/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
    <link rel="stylesheet" href="../static/style.css">
</head>
<body>

<main>

    <h1>Поиск постов</h1>

    <form action="search" method="get">
        <p>По вхождению слова</p>
        <input type="text" name="s">
        <input type="submit" value="Найти" class="button">
    </form>

    <hr>

    <a href="{{ url_for('loader_blueprint.add_post_form')}}" class="button">Добавить пост</a>

</main>
</body>
</html>

main/templates/post_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Все посты найденные по запросу "{{query}}"</title>
    <link rel="stylesheet" href="../static/style.css">
</head>
<body>
<main>

    <a href="{{ url_for('main_blueprint.page_index')}}" class="link">Назад</a>

    <h1>Посты по запросу "{{query}}"</h1>

    {% for post in posts %}
    <div class="post">
        <img src="{{ post.picture }}" width="100%" alt="">
        <p>{{ post.get_preview() }}</p>
    </div>
    <hr>
    {% endfor %}
    <a href="{{ url_for('loader_blueprint.add_post_form')}}" class="button">Добавить пост</a>

</main>
</body>
</html>